version: "3.9"
services:
  api:
    build: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///soc.db}
      - JWT_SECRET=${JWT_SECRET:-dev-secret}
      - API_KEY=${API_KEY:-dev-key-12345}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-25}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      - PAGERDUTY_ROUTING_KEY=${PAGERDUTY_ROUTING_KEY:-}
    ports: ["8000:8000"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes: ["./data:/app/data"]
  web:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on: [api]
    ports: ["5173:80"]
  proxy:
    image: nginx:alpine
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [api, web]
    ports: ["80:80"]
