name: backend-tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r backend/requirements.txt
          python - << 'PY'
from backend.soclib.parsers import ssh_auth, nginx, ufw, dns
assert ssh_auth.parse_line("Aug 20 21:55:01 demo sshd[111]: Failed password for invalid user admin from 1.2.3.4 port 51234 ssh2","demo")
assert nginx.parse_line('198.51.100.42 - - [20/Aug/2025:21:56:02 +0000] "GET /index.html HTTP/1.1" 200 1234 "-" "curl/7.88"',"demo")
assert ufw.parse_line("Aug 20 21:55:01 demo kernel: [..] [UFW BLOCK] IN=eth0 OUT= SRC=203.0.113.10 DST=10.0.0.5 PROTO=TCP DPT=8080","demo")
assert dns.parse_line("20-Aug-2025 21:56:00.000 client 198.51.100.42#55321 (abc.example.com): query: abc.example.com IN TXT +E","demo")
print("ok")
PY
